NUMPY PRACTICE CREATING ARRAYS

In [1]:
import numpy as np

1. Create a rank 2 (2D) array that resembles the matrix below.
[[11 12 13 14]
 [15 16 17 18]]

In [2]:
array = np.array([[11,12,13,14], [15,16,17,18]])
print(array)

[[11 12 13 14]
 [15 16 17 18]]


1. Create an array with 4 rows and 3 columns of zeros. Your results should look as below:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

In [4]:
zeros = np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.Create an array of ones that has 3 rows and 4 columns. Your results should look as below:
[[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]]

In [5]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Create an array containing integers 4 to 13 inclusive. Your results should look as below:
[4 5 6 7 8 9 10 11 12 13]

In [8]:
inclusive = np.arange(4, 14)
print(inclusive)

[ 4  5  6  7  8  9 10 11 12 13]


4. Create an array containing
[0., 1.5, 3., 4.5]

In [9]:
new_array = np.array([0, 1.5,3,4.5])
print(new_array)

[0.  1.5 3.  4.5]


5. Create a 2 by 2 array containing '4' in each position. Your results should look like this:
[[4 4]
 [4 4]]

In [11]:
fours = np.ones((2,2))*4
print(fours)

[[4. 4.]
 [4. 4.]]


6
. Create 2 matrices:
i. Identity matrix of size 4
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
ii. Diagonal matrix with [10,12] as the diagonals
[[10  0]
 [ 0 12]]

In [12]:
identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
diagonal = np.diag([10,12])
print(diagonal)

[[10  0]
 [ 0 12]]


7. Create a 3 by 3 array with random floats in [0, 10]. Your answer may be different because it is random but it should look something like this:
[[6.3685612  0.61720883 8.93157783]
 [3.69927617 5.79879583 7.62145626]
 [7.21895112 4.02011535 4.48844787]]

In [15]:
random = np.random.uniform(0,10, (3,3))
print(random)

[[6.52016882 2.19828334 4.32261182]
 [7.28381268 4.94830252 7.64591918]
 [2.84383246 3.42130339 2.85273301]]


8. Create a 3 by 3 array with random integers in [10, 20]. Your answer may be different because it is random but it should look something like this:
[[19 11 13]
 [10 11 13]
 [11 14 10]]

In [16]:
rand_int = np.random.randint(10,20, (3,3))
print(rand_int)

[[17 11 17]
 [16 10 16]
 [15 11 11]]


SLICING ARRAYS

1. Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
a. Get a subarray of the first row and first 2 columns. Your results should look like this:
[11 12]
b. Change all elements in 1st and second row to 0. Your results should look like this:
[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

In [17]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
subarray = myArray[0]
print(subarray)

[11 12 13]


In [22]:
change = myArray
change[[0,1]] = np.zeros(3)
print(change)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


2. Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [23]:
reverse = np.arange(0,21)
reverse = reverse[::-1]
print(reverse)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


RESHAPING
Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16]])
Reshape the array to an array with 3 rows. Your results should look like this:
[[11 12]
 [13 14]
 [15 16]]

In [25]:
myArray = np.array([[11,12,13], [14,15,16]])
reshape = np.transpose(myArray)
print(reshape)

[[11 14]
 [12 15]
 [13 16]]


MATH
Use this array for the following practice:
myArray = np.arange(10)
1. Find the square of every number in array
2. Find the square root of every number in array
3. Multiply the square of each number in array with its respective square root

In [31]:
myArray = np.arange(10)
print(myArray)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
squares = np.square(myArray)
print(squares)

[ 0  1  4  9 16 25 36 49 64 81]


In [29]:
square_root = np.sqrt(myArray)
print(square_root)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [30]:
multiple = np.multiply(squares, square_root)
print(multiple)

[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


ADDING ELEMENTS
Use this array for the following practice:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
1. Add a new row of elements containing 20, 21 and 22
2. Add a new column of elements containing 30, 40 and 50

In [57]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
new_row = np.array([20,21,22])
new_array = np.vstack((myArray,new_row))
print(new_array)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [58]:
new_column = np.array([[30], [40], [50]])
new_array_2 = np.hstack((myArray, new_column))
print(new_array_2)

[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


INSERTING ELEMENTS
1. Add 1 column of 1 to this array: myArray = np.zeros((2,2))
2. Add 2 rows of 2 to the answer from part 1
3. Remove the last column
4. Remove the last row

In [59]:
myArray = np.zeros((2,2))
print(myArray)

[[0. 0.]
 [0. 0.]]


In [61]:
add_ones = np.vstack((myArray, np.array([1,1])))
print(add_ones)

[[0. 0.]
 [0. 0.]
 [1. 1.]]


In [64]:
add_two = np.vstack((add_ones, np.array([[2,2], [2,2]])))
print(add_two)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [2. 2.]
 [2. 2.]]


In [65]:
remove_last_col = np.delete(myArray, 1, axis=1)
print(remove_last_col)

[[0.]
 [0.]]


In [66]:
remove_last_row = np.delete(myArray, 1, axis =0)
print(remove_last_row)

[[0. 0.]]


DELETING ELEMENTS
Remove the elements from the middle column of this array:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
Your codes should look like this:
[[1 3]
 [4 6]
 [9 7]]

In [67]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print(myArray)

[[1 2 3]
 [4 5 6]
 [9 8 7]]


In [69]:
remove_mid = np.delete(myArray, 1, axis = 1)
print(remove_mid)

[[1 3]
 [4 6]
 [9 7]]
